[project]
name = "python-openai-cua"
version = "0.1.0"
description = "Kernel sample app for CUA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "kernel>=0.38.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
